### ISSUE TITLE
USB to IR connect

### ISSUE THREAD

**Issue by javiergentoo** [gisce/iec870ree#31]
Hello

I would like to connect directly to the meters with a USB to Infrared conector.
Could somebody help me, how use theses examples for this kind of connection ?

Thanks
Javier

**Comment by javiergentoo** [comment]
Hello 
How I can use it conecting without modem, directly to the USB ?

**Comment by ecarreras** [comment]
Hello @javiergentoo I think it's possible but we have to implement a new [PhysicalLayer](https://github.com/gisce/iec870ree/blob/52c1ff7b7b1a5c64a49fec4b8846b5467e1abf48/iec870ree/protocol.py#L448) as we implemented [Modem](https://github.com/gisce/iec870ree/blob/52c1ff7b7b1a5c64a49fec4b8846b5467e1abf48/iec870ree/modem.py#L18) and [Ip](https://github.com/gisce/iec870ree/blob/52c1ff7b7b1a5c64a49fec4b8846b5467e1abf48/iec870ree/ip.py#L20), at this moment we don't have implemented this layer because we only use this protocol in server side. 

But if you want to implement this we can help you and you can make a pull-request 💪🏻

**Comment by javiergentoo** [comment]
Hello Eduard
Thanks for your reply, I will try to do it,

**Comment by IgnacioHR** [comment]
I’m interested on this too. 
I’ve installed at home one SAGEM CX2000-9 and I purchased a KMK116 for reading it from the infrared connector.
Reading the documentation of the SAGEM CX2000 I first tried using IEC62056-21 but I receive no response from the meter.
I learn later that in Spain the meters use IEC870-5-102 so that might explain why I’ve been unable to read the meter.
So I’m planning to implement a new PhysicalLayer for the serial device (it looks trivial to do) but I feel a bit insecure moving forward because my lack of knowledge and lack of available documentation from the meter. In other words, if the meter is implementing IEC870-5-102 on the optical connection that is nowhere documented in the product documentation.
I’ll be happy to hear from other who already success in using the optical connection about how to do it. Also I’ll share my progress here if you don’t disagree.

**Comment by IgnacioHR** [comment]
Well, I’ve finished my test and the implementation of a serial physical layer (very simple) and I’ve had no success in using it. Here is what I’m doing:
```
(venv) ihr@electra:~/iec870ree $ python examples/serial_cliente.py -d 1 -p 1 -c 0
INFO:root:Started /dev/ttyUSB0 1 1 0
INFO:iec870ree.serial:try open port 0
INFO:iec870ree.serial:serial port /dev/ttyUSB0 opened
INFO:iec870ree.serial:read thread Starting
INFO:iec870ree:sending frame
 ----- FixedAsdu Begin -----
 RES: 0 PRM: 1 FCB: 0 FCV: 0 CF(cod. funcion): 9
 DER: 1
 checksum: 74 0x4a
 10:49:01:00:4a:16
----- FixedAsdu End -----
INFO:root:->10:49:01:00:4a:16
INFO:iec870ree:receiving frame
Traceback (most recent call last):
  File "/home/ihr/iec870ree/examples/serial_cliente.py", line 68, in <module>
    run_example(port, der, dir_pm, clave_pm)
  File "/home/ihr/iec870ree/examples/serial_cliente.py", line 25, in run_example
    link_layer.link_state_request()
  File "/home/ihr/iec870ree/examples/../iec870ree/protocol.py", line 443, in link_state_request
    raise ProtocolException("Link state request didn't get response")
iec870ree.protocol.ProtocolException: Protocol Exception: Link state request didn't get response
```
As you can see I receive nothing. I don’t know why. It looks like the meter is not working? or it has the optical port blocked? my distributor is UFD and they do not respond to my questions so I don’t know how to move forward. In any case I’ve made a pull request for anyone to test my code or help me determine what’s going on.

**Comment by tinogis** [comment]
A **SAGEM CX2000-9** meter is a PRIME meter. This technology meters usually does not implements iec-870-ree protocol. It uses DLMS/COSEM protocol.

**Comment by sergioitig** [comment]
@IgnacioHR hola, me interesa hacer la conexión directamente por serial en local, sin tener que hacer capa de transporte ni por IP ni por modem, es posible puedas publicar el script examples/serial_cliente.py, para poder testearlo yo a ver si puedo hacer conexión.
En cuanto a la conexión mediante el puerto óptico que has mencionado anteriormente, solo cumplen los fabricantes con el protocolo IEC62056-21 a nivel de hard pero no implementan el protocolo a nivel de soft, por lo que te puedes volver loco aplicando las peticiones OBIS que no responden nada, para eso este puerto es posible mandarle las tramas del protocolo IEC870-5-102 y utilizarlo.

muchas gracias de antemano

**Comment by IgnacioHR** [comment]
@sergioitig Te acabo de enviar el script por mail. Espero que te sirva y que podamos avanzar en este tema.

Saludos
Ignacio

**Comment by javiergentoo** [comment]
Hola @IgnacioHR podría disponer del script para probarlo ? 
Muchas Gracias

**Comment by sergioitig** [comment]
Hola os cuento cosas

Tengo el siguiente contador con este medido óptico
 
![IMG_20231127_104147_387](https://github.com/gisce/iec870ree/assets/37344948/89c4a516-b1e2-4dac-a96d-476dc4e2971e)

Porque con otros dos que tengo, envía la trama, pero no recibe, 
 
![IMG_20231127_104159_718](https://github.com/gisce/iec870ree/assets/37344948/6e620787-2b78-4f85-bcbb-f5bebdf0ee55)
![IMG_20231127_104209_981](https://github.com/gisce/iec870ree/assets/37344948/275273f7-5556-4276-9949-7ef5a7834ebb)

Puede que la conexión en los conversores los tenga mal, pero no funcionan el primero de ORBIS si funciona

El script abre el puerto serial, ahora estoy en win con el COM3, pero lo he probado con raspberrypi en un ttyUSB01 y también conecta bien

Me ha dado un error en el método read_integrated_totals, porque no está definido en el protocolo que tengo yo y he puesto otro método el de ext_read_instant_values y funciona perfectamente, no he tocado nada de tu script salvo lo parámetros, que por cierto no se pasarlos por consola, los he de poner directamente en el código, y he hecho un bucle infinito y me devuelve todo bien, pero al final me sale un error cuando llama a physical_layer.disconnect()
lo pongo en captura, sabeis que puede ser?
![aaa](https://github.com/gisce/iec870ree/assets/37344948/2eadd2c1-60eb-4603-a9bd-c1c8ad15f32f)

Si necesitáis mas info de lo que he hecho me decís
Gracias

**Comment by javiergentoo** [comment]
Hola @IgnacioHR muchisimas gracias. Hoy no podre pero cuando saque un tiempo lo pruebo y a ver que puedo aportar

**Comment by IgnacioHR** [comment]
@javiergentoo cuéntanos qué sonda óptica tienes a ver si encontramos más de una que funcione.

**Comment by javiergentoo** [comment]
Buenas, tengo una que compre en Circutor y tengo que buscarla, ya que ayer no la encontre para empezar a hacer las pruebas, ya os contare cuando la encuentre. :(

**Comment by javiergentoo** [comment]
Buenas 
Estoy haciendo las pruebas, pero no encuentra el modulo serial:
"import iec870ree.serial
ModuleNotFoundError: No module named 'iec870ree.serial'
Esta todo instalado "pip install iec870ree"
Me falta algo por instalar ?
Saludos
Javier

**Comment by IgnacioHR** [comment]
Los archivos están en un pull request que hice en este proyecto. Te paso una URL para que investigues desde ahí:

https://github.com/gisce/iec870ree/pull/38/files

**Comment by javiergentoo** [comment]
Gracias @IgnacioHR

**Comment by apanazo** [comment]
Hola.
Tengo cierta experiencia en la lectura de contadores, casi siempre desde aplicaciones comerciales, os comento los problemas que he tenido habitualmente, por si sirve de ayuda a alguien: (hay que decir que casi siempre mis lecturas son directas por puerto serie, o a través de un conversor ethernet-serial atacando el puerto serie del contador)
- Hardware (son un poco obvios y, por los comentarios, veo que a todos nos pasa)
    No todos los conversores usb-serial funcionan adecuadamente
    No todos los lectores IR funcionan, en mi caso, finalmente conseguí uno que funcionaba y lo guardo como oro en paño, tanto que lo he estado buscando y no lo encuentro (es un Actaris, hoy por hoy Itron).
- Software: ¿Habéis confirmado los parámetros para la comunicación serie por el puerto óptico? El contador puede tener configurado diferentes parámetros según el puerto del que se trate. Me he encontrado contadores con velocidades configuradas diferentes a los 9600 bps que suelen ser habituales (cuando no eran 9600 eran 19200), y sobre todo está el tema de la paridad, los contadores configurados para Endesa, y también los contadores en los que el encargado de lectura es REE, suelen estar configurados con 8E1, sin embargo los de Iberdrola suelen estar configurados con 8N1. Afortunadamente, la configuración de las comunicaciones se puede ver en el menú del contador, y así estar seguros de no estar dando palos de ciego. Analizando un poco el código he visto que da por hecho que son 9600 bps, y me ha parecido que no se especifica en ningún lugar la paridad, y mirando la documentación de PySerial si no se indica nada, por defecto toma 8N1.
No tengo a mano equipos para hacer pruebas, a ver si en las próximos días me hago con ellos, hago pruebas y comparto los resultados.
Saludos
Luis Javier

**Comment by apanazo** [comment]
Buenas, he podido hacer unas pruebas por el puerto infrarrojo con el modulo serial y el script de @IgnacioHR .
Al principio no recibía respuesta, recordé que en el contador que estaba la parametrización de las comunicaciones es 9600 8 E 1, así que tuve que forzar en serial.py a la paridad par, añadiendo "parity=serial.PARITY_EVEN" en la línea 41, quedando:
    self.sport = serial.Serial(self.serial_port, baudrate=9600, timeout=1, parity=serial.PARITY_EVEN) 
Con esto conseguí conectar y recibir respuestas, recibiendo al final el mismo error que @sergioitig . Esto creo que lo he corregido, modificando el serial.py, en el método read_port, en la línea 89, cambiando el "continue" existente por "break", quedando:
            if not response:
                break
Espero haberme explicado, y que os funcione.

Como información, para estas pruebas he utilizado un lector IR tipo Circutor Cirwatt Q30301, con conexion serie RS232, y conectado a un conversor USB-serie.

Saludos
